---
title: "Course Project 1"
author: "Federico Vera"
date: "11/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1- LOading the Data

We take the URL of the data and put it on a local directory with  a copy on Github, load the data into R



```{r data}
# URL address of the data
URL <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"

# download the file 
download.file(URL,destfile="./datastore/repdata_2Fdata_2Factivity.zip",method="auto")


# Unzip the file
unzip(zipfile="./datastore/repdata_2Fdata_2Factivity.zip",exdir="data")
 
data <- read.csv("data/activity.csv", header=TRUE)
clear_Data <- na.omit(data)

```

## Calculating Total number of steps per day

```{r steps}

steps_x_day <- aggregate(clear_Data$steps, by= list(Steps.Date= clear_Data$date), FUN = "sum")

```


## Plot total number steps each day

plot the number of steps  in the x axis, divided in 20 breaks, and the y shows
the frecuenci of how many days that quantity appear.

```{r plot steps x day echo="FALSE" }
hist(steps_x_day$x,
     breaks=20,
     main="Histogram total number steps x day",
     xlab= "Steps x day",
     ylab= "n° of days with this steps"
     )
```
```{R mean and median}

#Mean
mean(steps_x_day$x, na.rm=TRUE)

#Median
median(steps_x_day$x, na.rm=TRUE)

```
```{R Plot daily activity pattern}
avg_steps_x_interval <- aggregate(steps ~ interval, clear_Data, mean)

plot(avg_steps_x_interval$interval, avg_steps_x_interval$steps, type="l",
     col=1,
     main="Average number of steps by Interval",
     xlab="time interval",
     ylab="Average number of steps")


```